import type { IconKey } from "@/types/module"
import type { LucideIcon } from "lucide-react"

import {
  LayoutDashboard,
  Home,
  List,

  Users,
  UsersRound,
  User,
  UserCheck,
  UserPlus,
  UserMinus,
  UserCog,
  IdCard,

  GraduationCap,
  School,
  University,
  Book,
  BookOpen,
  Library,
  Notebook,
  NotebookPen,
  FileText,
  Presentation,
  Award,
  Medal,

  Calendar,
  Clock,
  Timer,
  Clipboard,
  ClipboardCheck,
  ClipboardList,

  BarChart,
  LineChart,
  PieChart,
  Percent,
  TrendingUp,
  TrendingDown,

  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  Key,
  Lock,
  Database,
  Server,
  Layers,
  Folder,
  Workflow,

  Code,
  CodeXml,
  Code2,
  Braces,
  Terminal,
  SquareCode,
  FileCode,
  Bug,
  GitBranch,
  GitCommit,
  GitPullRequest,
  Github,
  Cpu,
  Binary,
  Command,
  Wrench,
  Hammer,

  Search,
  Filter,
  Download,
  Upload,
  Edit,
  Check,
  XCircle,
  Bell,
  Star,
  Target,
  Rocket,
} from "lucide-react"

export const iconMap: Record<IconKey, LucideIcon> = {
  // Dashboard
  dashboard: LayoutDashboard,
  "layout-dashboard": LayoutDashboard,
  home: Home,
  menu: List,

  // Users
  users: Users,
  "users-round": UsersRound,
  person: User,
  people: Users,
  "user-check": UserCheck,
  "user-plus": UserPlus,
  "user-minus": UserMinus,
  "user-cog": UserCog,
  "id-card": IdCard,

  // Academic
  "graduation-cap": GraduationCap,
  school: School,
  university: University,
  book: Book,
  books: Book,
  "book-open": BookOpen,
  library: Library,
  notebook: Notebook,
  "notebook-pen": NotebookPen,
  "file-text": FileText,
  presentation: Presentation,
  certificate: Award,
  award: Award,
  medal: Medal,

  // Class
  calendar: Calendar,
  clock: Clock,
  timer: Timer,
  clipboard: Clipboard,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,

  // Reports
  "bar-chart": BarChart,
  "line-chart": LineChart,
  "pie-chart": PieChart,
  percent: Percent,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,

  // System
  settings: Settings,
  "settings-2": Settings2,
  security: Shield,
  shield: Shield,
  "shield-check": ShieldCheck,
  key: Key,
  lock: Lock,
  database: Database,
  server: Server,
  layers: Layers,
  folder: Folder,
  workflow: Workflow,

  // Code
  code: Code,
  "code-xml": CodeXml,
  "code-2": Code2,
  braces: Braces,
  terminal: Terminal,
  "square-code": SquareCode,
  "file-code": FileCode,
  bug: Bug,
  "git-branch": GitBranch,
  "git-commit": GitCommit,
  "git-pull-request": GitPullRequest,
  github: Github,
  cpu: Cpu,
  binary: Binary,
  command: Command,
  wrench: Wrench,
  hammer: Hammer,

  // Actions
  search: Search,
  filter: Filter,
  download: Download,
  upload: Upload,
  edit: Edit,
  check: Check,
  "x-circle": XCircle,
  bell: Bell,
  star: Star,
  target: Target,
  rocket: Rocket,
}
