export const mockGradebookResponse = {
  success: true,
  message: "Gradebook retrieved successfully",
  data: {
    columns: [
      {
        key: "col-final-exam",
        label: "Final Exam",
        assessmentTypeId: "type-final",
        assessmentTypeName: "Final Exam",
        weight: 0.2,
        gradingMethod: "AVERAGE",
        columnIndex: 1,
      },
      {
        key: "col-midterm",
        label: "Midterm Exam",
        assessmentTypeId: "type-midterm",
        assessmentTypeName: "Midterm Test",
        weight: 0.5,
        gradingMethod: "LATEST",
        columnIndex: 2,
      },
      {
        key: "col-quiz-1",
        label: "Quiz Chapter 1",
        assessmentTypeId: "type-quiz",
        assessmentTypeName: "Entrance Quiz",
        weight: 0.15,
        gradingMethod: "HIGHEST",
        columnIndex: 3,
      },
      {
        key: "col-quiz-2",
        label: "Quiz Chapter 2",
        assessmentTypeId: "type-quiz",
        assessmentTypeName: "Entrance Quiz",
        weight: 0.15,
        gradingMethod: "HIGHEST",
        columnIndex: 4,
      },
      {
        key: "FINAL_SCORE",
        label: "Final Score",
        assessmentTypeId: null,
        assessmentTypeName: null,
        weight: null,
        gradingMethod: null,
        columnIndex: 5,
      },
      {
        key: "IS_PASSED",
        label: "Passed",
        assessmentTypeId: null,
        assessmentTypeName: null,
        weight: null,
        gradingMethod: null,
        columnIndex: 6,
      },
    ],

    rows: {
      items: [
        {
          userId: "u1",
          fullName: "Alice Johnson",
          values: {
            "col-final-exam": 7.5,
            "col-midterm": 8.2,
            "col-quiz-1": 8,
            "col-quiz-2": 8.5,
            FINAL_SCORE: 8.15,
            IS_PASSED: true,
          },
        },
        {
          userId: "u2",
          fullName: "Carol Davis",
          values: {
            "col-final-exam": 9.25,
            "col-midterm": 9.2,
            "col-quiz-1": 9.5,
            "col-quiz-2": 9.8,
            FINAL_SCORE: 9.39,
            IS_PASSED: true,
          },
        },
        {
          userId: "u3",
          fullName: "Bob Wilson",
          values: {
            "col-final-exam": 5.75,
            "col-midterm": 4,
            "col-quiz-1": 5.5,
            "col-quiz-2": 4.8,
            FINAL_SCORE: 4.8,
            IS_PASSED: false,
          },
        },
        {
          userId: "u4",
          fullName: "John Doe",
          values: {
            "col-final-exam": 8.5,
            "col-midterm": 7,
            "col-quiz-1": 8,
            "col-quiz-2": 9,
            FINAL_SCORE: 7.9,
            IS_PASSED: true,
          },
        },
        {
          userId: "u5",
          fullName: "David Lee",
          values: {
            "col-final-exam": 6.1,
            "col-midterm": 5.5,
            "col-quiz-1": 6.2,
            "col-quiz-2": 5.5,
            FINAL_SCORE: 5.83,
            IS_PASSED: false,
          },
        },
      ],

      pagination: {
        page: 0,
        pageSize: 10,
        totalElements: 5,
        totalPages: 1,
      },
    },
  },
}
